## This first function creates a list of functions to
### 1. set the value of the matrix
### 2. get the value of the matrix
### 3. set the value of the inverse of the matrix
### 4. get the value of the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
		inv <- NULL
		set <- function(y) {
			x <<- y
			inv <<- NULL
		}
		get <- function() x
		set_inv <- function(inverted) inv <<- inverted
		get_inv <- function() inv
		list(set=set, get=get, set_inv=set_inv, get_inv=get_inv)
}


## Write a short comment describing this function

## This second function calculates the inverse of the matrix included in the list generated by the previous function.
## However, it first checks to see if the inverse of the matrix has already been calculated.
## If so, it gets the mean from the cache and skips the computation.
## Otherwise, it calculates the mean of the data and sets the value of the inverse in the cache via the set_inv function.

cacheSolve <- function(x, ...) {
		inv <- x$get_inv()
		if(!is.null(inv)) {
			message("getting cached data")
			return(inv)
		}
		data <- x$get()
		inv <- solve(data, ...)
		x$set_inv(inv)
		inv
}
